# Generated by Django 4.2.7 on 2025-09-16 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('tags', models.JSONField(default=list, help_text='List of problem tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.IntegerField(default=0, help_text='Confidence level 0-100')),
                ('frequency_days', models.IntegerField(default=1, help_text='Days between reviews')),
                ('last_attempted', models.DateTimeField(blank=True, null=True)),
                ('next_due', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempts_count', models.IntegerField(default=0)),
                ('solved_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_problems', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_due'],
                'unique_together': {('user', 'problem')},
            },
        ),
    ]
